proCon.words = require('random-words')
require('./Observable.js')
require('./Item.js')
require('./Pro.js')
require('./Con.js')
require('./Side.js')
require('./Pros.js')
require('./Cons.js')
require('./Controller.js')